[package]
name = "deli_cat_essen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nze_game_sdl = { path = "lib/nze_game_sdl/", version = "0.1.2" }
rand = { version = "0.8" }